#define BOARD_ENABLE_I2S1
#define BOARD_I2S1_TPLG "i2s-jack"

#define BOARD_AUDIO_CODEC_HID "ESSX8316"
#define BOARD_CODEC_I2C "\\_SB.I2C7"
#define BOARD_CODEC_I2C_ADDR 0x11
#define BOARD_CODEC_GPIO "\\_SB.GPI1"
#define BOARD_CODEC_GPIO_PIN GPIO_PIN_PD5