#define BOARD_ENABLE_I2S0
#define BOARD_I2S0_TPLG "i2s-jack"

#define BOARD_AUDIO_CODEC_HID "ESSX8388"
#define BOARD_CODEC_I2C "\\_SB.I2C3"
#define BOARD_CODEC_I2C_ADDR 0x10
#define BOARD_CODEC_GPIO "\\_SB.GPI3"
#define BOARD_CODEC_GPIO_PIN GPIO_PIN_PB2