# @file
# GNUmakefile for building the FitGen utility.
#
# Copyright (c) 2010-2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
MAKEROOT ?= $(EDK_TOOLS_PATH)/Source/C

APPNAME = FitGen

OBJECTS = FitGen.o

include $(MAKEROOT)/Makefiles/app.makefile

LIBS = -lCommon

