# @file
# makefile for building the FitGen utility.
#
# Copyright (c) 2010-2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.common

APPNAME = FitGen

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = FitGen.obj

!INCLUDE $(EDK_TOOLS_PATH)\Source\C\Makefiles\ms.app

